language: "en_US"
auctionIntervalTicks: 72000
bidTimeoutTicks: 600
marketPlaySound: true
marketBroadcast: true
# default 120 sec
marketBroadcastCooldown: 120
#offer slots limit
#permission node heh.offer.[group]
marketSlot:
    default: 10
    builder: 15
database:
    provider: sqlite
    sqlite_file: HamsterEcoHelper.db
    mysql_url: 
    mysql_username: 
    mysql_password: 
    mysql_jdbc_driver: 
